import type { Metadata } from "next";
import {Inter} from "next/font/google"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar" // "@/" is used to access the outermost folders inside my-app folder

const inter = Inter({subsets:['latin']});

export const metadata = {
  title: "I am a blog",
  description: "Generated by create next app"
};

export default function RootLayout({children }){
  return (
    <html>
       <NavBar/>
      <body className="min-h-full flex flex-col">{children}</body>

    </html>
  );
}
